# docker-compose.yml
version: "3.7"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        networks:
            - backend-db
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: mydb
        ports:  
            - 3308:3306
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    backend:
        image: samxkimomni/webapp:0.0.2-SNAPSHOT
        restart: always
        networks:
            - backend-db
        ports:
            - 8090:8080
        environment:
            spring.datasource.url: "jdbc:mysql://db:3306/mydb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false"
            spring.datasource.username: "root"
            spring.datasource.password: "example"
        depends_on:
            db:
                condition: service_healthy
networks:
    backend-db: